### ISSUE TITLE
Order is significant in rule definition

### ISSUE THREAD

**Issue by jrib-eg** [lab-v2/pyreason#20]
Is order meant to be significant in the rule definitions?

I expected these two rules to be equivalent, but was surprised to find pyreason had different behavior for each rule:

```
working_rule = 'has_blue(x) <-1 is_member_of(y,x), blue(y)'
broken_rule = 'has_blue(x) <-1 blue(y), is_member_of(y,x)'
```

Here are two examples to explain what I am seeing.  The only difference is that Example 1 uses `working_rule` while Example 2 uses `broken_rule`.

### Example 1
```
# bug1.py
import networkx as nx
import pyreason as pr

pr.settings.verbose = True     # Print info to screen
pr.settings.atom_trace = True  # This allows us to view all the atoms that have made a certain rule fire

g = nx.DiGraph()
g.add_nodes_from(['Group1'])
g.add_nodes_from(['User1'])
g.add_edge('User1', 'Group1', is_member_of=1)

pr.load_graph(g)

working_rule = 'has_blue(x) <-1 is_member_of(y,x), blue(y)'
broken_rule = 'has_blue(x) <-1 blue(y), is_member_of(y,x)'
rule = working_rule

pr.add_rule(rule, 'ui_rule')  # works
pr.add_fact(pr.Fact(name='fact1', component='User1', attribute='blue', bound=[1, 1], start_time=0, end_time=2))

interpretation = pr.reason(timesteps=2)
dataframes = pr.filter_and_sort_nodes(interpretation, ['has_blue'])
for t, df in enumerate(dataframes):
    print(f'TIMESTEP - {t}')
    print(df)
    print()
```

Output:

```
$ python bug1.py
Timestep: 0
Timestep: 1
Timestep: 2

Converged at time: 2
Fixed Point iterations: 3
TIMESTEP - 0
Empty DataFrame
Columns: [component, has_blue]
Index: []

TIMESTEP - 1
  component    has_blue
0    Group1  [1.0, 1.0]

TIMESTEP - 2
  component    has_blue
0    Group1  [1.0, 1.0]
```

This output is what I expected since `Group1` has a member with `blue`.

### Example 2

```
# bug2.py
import networkx as nx
import pyreason as pr

pr.settings.verbose = True     # Print info to screen
pr.settings.atom_trace = True  # This allows us to view all the atoms that have made a certain rule fire

g = nx.DiGraph()
g.add_nodes_from(['Group1'])
g.add_nodes_from(['User1'])
g.add_edge('User1', 'Group1', is_member_of=1)

pr.load_graph(g)

working_rule = 'has_blue(x) <-1 is_member_of(y,x), blue(y)'
broken_rule = 'has_blue(x) <-1 blue(y), is_member_of(y,x)'
rule = broken_rule

pr.add_rule(rule, 'ui_rule')  # works
pr.add_fact(pr.Fact(name='fact1', component='User1', attribute='blue', bound=[1, 1], start_time=0, end_time=2))

interpretation = pr.reason(timesteps=2)
dataframes = pr.filter_and_sort_nodes(interpretation, ['has_blue'])
for t, df in enumerate(dataframes):
    print(f'TIMESTEP - {t}')
    print(df)
    print()
```

```
$ python bug2.py
Timestep: 0
Timestep: 1
Timestep: 2

Converged at time: 2
Fixed Point iterations: 3
TIMESTEP - 0
Empty DataFrame
Columns: [component, has_blue]
Index: []

TIMESTEP - 1
Empty DataFrame
Columns: [component, has_blue]
Index: []

TIMESTEP - 2
Empty DataFrame
Columns: [component, has_blue]
Index: []
```

This output is not what I expected since `Group1` has a `blue` member.  `has_blue(Group1)` should be true at TIMESTEP 2.

**Comment by dyumanaditya** [comment]
Hi @jrib-eg,

Order is in fact important when writing rules. There are two types of clauses in PyReason rules (and graph reasoning in general) `node` clauses and `edge` clauses. Taking your 2nd rule as an example:
```
broken_rule = 'has_blue(x) <-1 blue(y), is_member_of(y,x)'
```
For the first (node) clause `blue(y)`,  since the variable `y` is not in the head of the rule (`has_blue`) nor has it been seen before (in any previous clauses), it will be gounded to be the set of all neighbors of `x`. Therefore since `x` has no neighbors with this attribute, the rule will be declared false and not work.

In your 1st rule:
```
working_rule = 'has_blue(x) <-1 is_member_of(y,x), blue(y)'
```
The first (edge) clause `is_member_of` has the variable `y` **AND** `x` which figures also in the head of the rule. For this clause, `y` will be grounded with nodes that have target (reverse neighbors) `x`. This is very different from the previous node clause that takes `y` to be the neighbors of `x`.

The reason for this difference in clauses stems from the fact that we are doing graph reasoning and want to make use of the connections in the Knowledge Graph to help speed up inference. If we allowed `y` to be every node in the graph instead of just the neighbors of `x`, we don't make use of the graphical structure for node clauses and a rule such as `head(x) <- predicate(y)` will make no sense.

We may change this behaviour in the future to make `y` represent all nodes in the graph but for now we use the graph to ground values of `y` to be the neighbors of the variable in the head.

**Comment by dyumanaditya** [comment]
Feel free to re-open or post any other questions, I'd be happy to help.

**Comment by dyumanaditya** [comment]
> I'm interpreting this to mean: for each node `x` in the knowledge graph, the rule is grounded to all neighbors of `x`. Is that the wrong way to think about this statement?

Yes, `y` will be grounded to all neighbors of `x`.



> But when `x` is the node `Group1`, it does have a neighbor with the `blue` attribute, doesn't it?

No it doesn't look like `Group1` has a neighbor with `blue` from the way you defined your edges:
```
g.add_edge('User1', 'Group1', is_member_of=1)
```
This is a directed edge which means only `User1` has  a neighbor. We consider neighbors to be along directed edges.
